# -*- coding: utf-8 -*-
"""Object Detection using yolo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jsfmKeAmevfvUOh1Fo0AcrCyl_k5Y9U9

# **Object Detection in Image Through YOLO**
"""

# Step 1: Download required files
!wget https://raw.githubusercontent.com/pjreddie/darknet/master/data/coco.names -O coco.names
!wget https://raw.githubusercontent.com/pjreddie/darknet/master/cfg/yolov3.cfg -O yolov3.cfg
!wget https://github.com/AlexeyAB/darknet/releases/download/darknet_yolo_v3_optimal/yolov3.weights -O yolov3.weights
!wget https://raw.githubusercontent.com/pjreddie/darknet/master/data/dog.jpg -O dog.jpg

# Step 2: Import dependencies
import numpy as np
import cv2
import time
from google.colab.patches import cv2_imshow

# Step 3: Load image
image = cv2.imread('dog.jpg')
(H, W) = image.shape[:2]

# Step 4: Load class labels
with open('coco.names', 'r') as f:
    LABELS = f.read().strip().split('\n')

# Step 5: Assign colors
np.random.seed(42)
COLORS = np.random.randint(0, 255, size=(len(LABELS), 3), dtype="uint8")

# Step 6: Load YOLO model
print("[INFO] Loading YOLOv3...")
net = cv2.dnn.readNetFromDarknet('yolov3.cfg', 'yolov3.weights')

# Get output layer names
ln = net.getLayerNames()
ln = [ln[i - 1] for i in net.getUnconnectedOutLayers().flatten()]

# Step 7: Create blob and run forward pass
blob = cv2.dnn.blobFromImage(image, 1/255.0, (416, 416), swapRB=True, crop=False)
net.setInput(blob)

start = time.time()
layerOutputs = net.forward(ln)
end = time.time()
print("[INFO] YOLO took {:.2f} seconds".format(end - start))

# Step 8: Process detections
confidence_threshold = 0.5
nms_threshold = 0.3

boxes = []
confidences = []
classIDs = []

for output in layerOutputs:
    for detection in output:
        scores = detection[5:]
        classID = np.argmax(scores)
        confidence = scores[classID]

        if confidence > confidence_threshold:
            box = detection[0:4] * np.array([W, H, W, H])
            (centerX, centerY, width, height) = box.astype("int")

            x = int(centerX - width / 2)
            y = int(centerY - height / 2)

            boxes.append([x, y, int(width), int(height)])
            confidences.append(float(confidence))
            classIDs.append(classID)

# Step 9: Apply Non-Max Suppression
idxs = cv2.dnn.NMSBoxes(boxes, confidences, confidence_threshold, nms_threshold)

# Step 10: Draw results
if len(idxs) > 0:
    for i in idxs.flatten():
        x, y = boxes[i][0], boxes[i][1]
        w, h = boxes[i][2], boxes[i][3]

        color = [int(c) for c in COLORS[classIDs[i]]]
        cv2.rectangle(image, (x, y), (x + w, y + h), color, 2)
        text = f"{LABELS[classIDs[i]]}: {confidences[i]:.2f}"
        cv2.putText(image, text, (x, y - 5), cv2.FONT_HERSHEY_SIMPLEX, 0.5, color, 2)

# Step 11: Display image in Colab
cv2_imshow(image)

"""# **Object Detection Real Time in a Video Through YOLO**"""

# Step 1: Download necessary files (run only once)
!wget https://raw.githubusercontent.com/pjreddie/darknet/master/data/coco.names -O coco.names
!wget https://raw.githubusercontent.com/pjreddie/darknet/master/cfg/yolov3.cfg -O yolov3.cfg
!wget https://github.com/AlexeyAB/darknet/releases/download/darknet_yolo_v3_optimal/yolov3.weights -O yolov3.weights
!wget https://github.com/opencv/opencv/raw/master/samples/data/vtest.avi -O test_video.avi

import cv2
import numpy as np
import time
from google.colab.patches import cv2_imshow

# Load class labels
with open('coco.names', 'r') as f:
    LABELS = f.read().strip().split('\n')

# Assign colors for each label
np.random.seed(42)
COLORS = np.random.randint(0, 255, size=(len(LABELS), 3), dtype='uint8')

# Load YOLOv3 model
print("[INFO] Loading YOLOv3 weights and config...")
net = cv2.dnn.readNetFromDarknet('yolov3.cfg', 'yolov3.weights')
ln = net.getLayerNames()
ln = [ln[i - 1] for i in net.getUnconnectedOutLayers().flatten()]

# Load pre-recorded video
cap = cv2.VideoCapture("test_video.avi")

while True:
    ret, frame = cap.read()
    if not ret:
        break

    (H, W) = frame.shape[:2]

    # Create blob from frame
    blob = cv2.dnn.blobFromImage(frame, 1/255.0, (416, 416), swapRB=True, crop=False)
    net.setInput(blob)

    start = time.time()
    layerOutputs = net.forward(ln)
    end = time.time()

    boxes = []
    confidences = []
    classIDs = []

    confidence_threshold = 0.5
    nms_threshold = 0.3

    # Process detections
    for output in layerOutputs:
        for detection in output:
            scores = detection[5:]
            classID = np.argmax(scores)
            confidence = scores[classID]

            if confidence > confidence_threshold:
                box = detection[0:4] * np.array([W, H, W, H])
                (centerX, centerY, width, height) = box.astype("int")

                x = int(centerX - width / 2)
                y = int(centerY - height / 2)

                boxes.append([x, y, int(width), int(height)])
                confidences.append(float(confidence))
                classIDs.append(classID)

    # Apply Non-Max Suppression
    idxs = cv2.dnn.NMSBoxes(boxes, confidences, confidence_threshold, nms_threshold)

    # Draw results
    if len(idxs) > 0:
        for i in idxs.flatten():
            x, y = boxes[i][0], boxes[i][1]
            w, h = boxes[i][2], boxes[i][3]

            color = [int(c) for c in COLORS[classIDs[i]]]
            cv2.rectangle(frame, (x, y), (x + w, y + h), color, 2)
            text = f"{LABELS[classIDs[i]]}: {confidences[i]:.2f}"
            cv2.putText(frame, text, (x, y - 5), cv2.FONT_HERSHEY_SIMPLEX, 0.5, color, 2)

    # Display the output frame
    from google.colab.patches import cv2_imshow
    cv2_imshow(frame)

    # Press 'q' to quit
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

# Clean up
cap.release()
cv2.destroyAllWindows()